### ISSUE TITLE
[Bug] Tile only triggers with selected animation type when entering token is whitelisted

### ISSUE THREAD

**Issue by ThreeRaccoonsInACoat** [Couls/hey-wait#10]
Replication Steps:

1. Create HW! tile
2. Set trigger animation type
3. Have player move token onto HW! tile.

Versioning Information:
- Foundry v 11.305
- PF2e v. 5.1.2
- Hey, Wait! v. 0.7.5

**Comment by Couls** [comment]
Fixed in v0.7.6
