### ISSUE TITLE
Can't revert Hey, wait! tile from active to inactive and vica-versa

### ISSUE THREAD

**Issue by TrofimSelbs** [Couls/hey-wait#12]
Hey, thank you for you wonderful module! I noticed a small issue, I can't use Hand icon to change the tile's states. Neither from active to inactive, nor the other way around. I am on 5e, foundry v11 315

https://github.com/Couls/hey-wait/assets/124184162/5b7c75f9-a277-4804-b10d-76019eeb2c68

**Comment by Couls** [comment]
fixed in 0.7.7
