### ISSUE TITLE
Triggering a tile moves token to the upper-left corner/left side 

### ISSUE THREAD

**Issue by SilvesTheRog** [Couls/hey-wait#2]
Using 0.7.2 version causes a token to move to the upper-left corner/left side of a tile upon triggering. Other modules that would mess with any tiles were disabled during the test.

![image](https://user-images.githubusercontent.com/127493227/224287329-e50ca95f-a262-4362-821c-25403b8519ce.png)

**Comment by SilvesTheRog** [comment]
It also happens on every possible animation type. If there are no corners, a token moves to the top.

**Comment by Couls** [comment]
I see, I forgot to account for tiles this large, thanks for reporting!

**Comment by Couls** [comment]
I'll leave this open until I can get to and resolve it

**Comment by Couls** [comment]
Resolved with latest release

**Comment by clickexe** [comment]
Having a similar problem, except tokens are being moved to the bottom right, even with tiles only filling one grid space.
![image](https://user-images.githubusercontent.com/60618333/226130013-68eb6988-6467-4850-9dc7-0d9240f4a382.png)
![image](https://user-images.githubusercontent.com/60618333/226130024-79d59d20-1ac3-42d4-badf-cfa8b6b79982.png)
