### ISSUE TITLE
[Bug] Trigger animation !? is shown behind darkness & foreground image

### ISSUE THREAD

**Issue by yjeroen** [Couls/hey-wait#3]
Behind scene foreground layer:
![image](https://user-images.githubusercontent.com/1303988/224315421-aa8281cf-773a-4908-b67f-7025363346eb.png)

Also behind darkness:
![image](https://user-images.githubusercontent.com/1303988/224315609-e72ac27d-c493-4806-9791-c1618ffc8f57.png)

**Comment by Couls** [comment]
Thanks for reporting, i'll get on this soon

**Comment by Couls** [comment]
Resolved with the latest release
