### ISSUE TITLE
 Triggering a tile shunts the token

### ISSUE THREAD

**Issue by nolomarsh** [Couls/hey-wait#5]
Whenever a token moves onto a tile and triggers it, the token is moved either one tile to it's right, one tile down, or one tile diagonally down-right. As shown below, it will even push PCs through walls.

Update: upon further troubleshooting, it would seem that the token is moved one space to the right if it enters the tile from above or below, and the token is moved one space down if it enters the tile from the left or right. If the token enters the tile at any diagonal, the token is not shunted.

![Screenshot 2023-04-18 at 6 22 43 PM](https://user-images.githubusercontent.com/84742667/232925786-3b091736-6dde-4f45-8a95-224cdf259a2c.png)
![Screenshot 2023-04-18 at 6 29 46 PM](https://user-images.githubusercontent.com/84742667/232926602-61d086cd-5a1f-44dd-ae58-784f36d8bb25.png)

**Comment by alcameron** [comment]
+1
Having the exact same issue with the latest version of Foundry and this module

**Comment by Couls** [comment]
thanks for submitting the issue, i'll look into fixing this now

**Comment by Couls** [comment]
Fixed in v0.7.4
