### ISSUE TITLE
Feature request: Support for level module

### ISSUE THREAD

**Issue by diwako** [Couls/hey-wait#7]
Hey,
I wanted to request support for the [Levels](https://foundryvtt.com/packages/levels) and [Wall height](https://foundryvtt.com/packages/wall-height) modules.

Effectively this will mean hey wait will need to check which elevation a token is and on which elevation levels the hey wait field is visible.

**Comment by Couls** [comment]
Good idea, I'll try to get this in for the next version

**Comment by Couls** [comment]
Elevation checks added in 0.7.5
